### ISSUE TITLE
Output has incorrect contexts and misplaced tunables

### ISSUE THREAD

**Issue by Wildbrick142** [hectorredx/GTAV-Tunables#2]
Taking the [pcros](https://github.com/hectorredx/GTAV-Tunables/blob/f1aa3cf63bfcd758d3d656c446247302be71eda0/tunables-pcros.json) output as an example, it has contexts that should not be there; MP_FM_MEMBERSHIP, which is simply not a thing on PC/PS4/X1, and MP_CNC, which is unused everywhere.

9848F4A3 is listed under BASE_GLOBALS in the output, but that hash actually corresponds to a FAKE_XP_MULTIPLIER tunable under the CONTENT_MODIFIER_0 context.

Furthermore, none of the unnamed hashes seem to be reversed in the output. 84EB090A is correctly listed under CD_GLOBAL, but its real hash is A13B434D (84EB090A with the hash of CD_GLOBAL subtracted from it.) It would be nice if they were reversed as that would help to cross-check the unknown tunables with the scripts faster.

Here's an example of what it should look like: https://gist.github.com/Wildbrick142/b4645c960a4198d4658a5973fa4789ee
The general rule is that the list in the original file is split up in sections by contexts, so if the first tunable is a part of BASE_GLOBALS, and the third tunable is also a part of BASE_GLOBALS, then the second tunable must be BASE_GLOBALS as well. They are never mixed.
This also means that 8B7D3320 is not a part of CD_GLOBAL, but is either a part of BASE_GLOBALS, MP_GLOBAL, or is its own thing altogether (I left it as unknown in the example output above, it's one of those annoying executable-only tunables that I don't know how to get a list of so I have no means of verifying where exactly does it belong). Same with B827BB11 is a part of BASE_GLOBALS, not CD_GLOBAL, 2B09C851 is a part of BASE_GLOBALS and not MP_CNC, etc.

Also, unrelated to the issue, would it be possible to have an option that does not alphabetically sort the tunables and instead keeps the list in the same order as the original file?

**Comment by hectorredx** [comment]
> The general rule is that the list in the original file is split up in sections by contexts, so if the first tunable is a part of BASE_GLOBALS, and the third tunable is also a part of BASE_GLOBALS, then the second tunable must be BASE_GLOBALS as well. They are never mixed.

Thank you so much for the feedback, I totally didn't know about this point.
I'll make the necessary adjustments as well as provide both sorted and unsorted outputs, probably via a nice HTML view.

**Comment by ShinyWasabi** [comment]
>This also means that 8B7D3320 is not a part of CD_GLOBAL, but is either a part of BASE_GLOBALS, MP_GLOBAL, or is its own thing altogether (I left it as unknown in the example output above, it's one of those annoying executable-only tunables that I don't know how to get a list of so I have no means of verifying where exactly does it belong).

8B7D3320 is the "bonus" list/context which is related to some anti-cheat stuff like cheat logs. from what Tez told me, It's base64 encoded on top of additional cryptography methods.

**Comment by hectorredx** [comment]
Hey @Wildbrick142, Thanks again for the feedback, the script now outputs the same output in your example, except for using the content name instead of the root content ID.
Regarding content, do yo know any source that has all id's? because I scraped [62K](https://github.com/hectorredx/GTAV-Tunables/blob/master/src/static/jobs_dictionary.json) so far and there are still some missing.

**Comment by Wildbrick142** [comment]
> 8B7D3320 is the "bonus" list/context which is related to some anti-cheat stuff like cheat logs. from what Tez told me, It's base64 encoded on top of additional cryptography methods.

i knew that too, but i don't know what tunable context it would belong to (base_globals? mp_global? or is it its own thing?) and that's not something i know how to find either.


> Hey @Wildbrick142, Thanks again for the feedback, the script now outputs the same output in your example, except for using the content name instead of the root content ID. Regarding content, do yo know any source that has all id's? because I scraped [62K](https://github.com/hectorredx/GTAV-Tunables/blob/master/src/static/jobs_dictionary.json) so far and there are still some missing.

great work on the update. and sorry for a month late reply. i don't know how to get the content id names, the ones i had were scraped from other sources. either alloc8or or the owner of gtalens.com would be the right people to ask about those
